language: python
python:
  - "3.5.3"

install:
  - python3 setup.py install
  - pip3 install python-coveralls
  - pip3 install coverage
  - pip3 install nose

script: 
  - nosetests --with-coverage

after_success:
  - coveralls
