version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

            # - run:
            #     name: install dependencies
            #     command: |
            #       python3 -m venv venv
            #       . venv/bin/activate
            #       pip3 install -r requirements.txt

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - save_cache: # special step to save the dependency cache
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run: # run tests
          name: Install dependencies, Run Test and Coverage
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

            ./cc-test-reporter before-build
            nosetests --with-coverage
            ./cc-test-reporter after-build --exit-code $?
